name: iOS CI

on:
  pull_request: { branches: [main] }
  push:        { branches: [main] }

concurrency:
  group: ios-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Show Xcode & simulators
        run: |
          xcodebuild -version
          xcrun simctl list devices available | sed -n '1,80p'

      - name: Build (generic iOS Simulator)
        run: |
          set -o pipefail
          xcodebuild \
            -project FairSplit.xcodeproj \
            -scheme FairSplit \
            -sdk iphonesimulator \
            -destination 'generic/platform=iOS Simulator' \
            -configuration Debug \
            -parallel-testing-enabled NO \
            build

      - name: Test (if tests exist)
        run: |
          set -o pipefail
          if ls -1d */*Tests.swift */*Tests/*.swift >/dev/null 2>&1; then
            xcodebuild test \
              -project FairSplit.xcodeproj \
              -scheme FairSplit \
              -sdk iphonesimulator \
              -destination 'generic/platform=iOS Simulator' \
              -parallel-testing-enabled NO \
              -maximum-parallel-testing-workers 1
          else
            echo "No tests yet — skipping."
          fi
